# Generated by Django 5.0.7 on 2024-07-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_provider', models.CharField(max_length=100)),
                ('data_format', models.SlugField(max_length=10)),
                ('degree_of_aggregation', models.IntegerField(choices=[(0, 'Raw: data in its original form without any processing or aggregation'), (1, 'Aggregated: data aggregated according to certain criteria (for example, averages, totals)'), (2, 'Anonymized: data from which personally identifiable information has been removed or masked to protect privacy'), (3, 'Summarized: data presented in summarized form (e.g., pivot tables, graphs)')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
