# Generated by Django 5.0.7 on 2024-07-22 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeOfAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='researchmetadata',
            options={'verbose_name': 'Research Metadata', 'verbose_name_plural': 'Research Metadata'},
        ),
        migrations.AlterField(
            model_name='researchmetadata',
            name='data_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_metadata', to='meta_form.dataformat'),
        ),
        migrations.AlterField(
            model_name='researchmetadata',
            name='degree_of_aggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_metadata', to='meta_form.degreeofaggregation'),
        ),
    ]
